name: 'Conventional commit cocogitto action'
description: 'Check conventional commits compliance and/or automatically release new version'
branding:
  icon: 'git-commit'
  color: 'red'
author: 'Paul Delafosse'

inputs:
  release:
    description: 'Perform a release with cog bump --auto'
    required: false
    default: 'false'
  check:
    description: 'Perform a conventional commit check with cog --check'
    required: false
    default: 'true'
  check-latest-tag-only:
    description: 'Check commit history from latest tag to HEAD'
    required: false
    default: 'false'
  git-user:
    description: 'Git user.name configuration'
    required: false
    default: 'cog-bot'
  git-user-email:
    description: 'Git user.email configuration'
    required: false
    default: 'cog@demo.org'
outputs:
  version:
    description: "Version released"
    value: ${{ steps.cog.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Set environment variables (Windows-safe paths)
      run: |
        # Convert to forward slashes
        echo "GITHUB_ACTION_PATH=$(echo $GITHUB_ACTION_PATH | sed 's/\\/\//g')" >> $GITHUB_ENV
      shell: bash

    - run: echo Installing cocogitto
      shell: bash

    - id: install
      run: $GITHUB_ACTION_PATH/install.sh $GITHUB_ACTION_PATH
      shell: bash

    - run: echo Running cocogitto
      shell: bash

    - id: add-to-path
      shell: sh
      run: |
        echo "Bin path from workflow: $GITHUB_ACTION_PATH/.local/bin"
        echo "$GITHUB_ACTION_PATH/.local/bin" >> $GITHUB_PATH

    - id: cog
      run: |
        $GITHUB_ACTION_PATH/cog.sh    \
        ${{ inputs.check }} \
        ${{ inputs.check-latest-tag-only }} \
        ${{ inputs.release }}               \
        ${{ inputs.git-user }}              \
        ${{ inputs.git-user-email }} \
        "$GITHUB_ACTION_PATH/cog.exe"
      shell: bash
